### ISSUE TITLE
"Unresolvable JSON pointer" when jsonschema>=4.18.1

### ISSUE THREAD

**Issue by EliahKagan** [EliahKagan/pylint-sarif#19]
When `pylint-sarif-unofficial` (this software) is used with `jsonschema` at version 4.18.1 or higher--but *not* at 4.17.\* and *not* at 4.18.0--it gives the error:

```text
jsonschema.exceptions._RefResolutionError: Unresolvable JSON pointer: 'definitions/messageClass'
```

Here's an example of full error output, running `pylint2sarif` on itself:

```text
(pylint-sarif-unofficial-py3.11) ek@Glub:~/repos-wsl/pylint-sarif (develop +%=)$ pylint2sarif src/pylint2sarif.py
Traceback (most recent call last):
  File "/home/ek/.cache/pypoetry/virtualenvs/pylint-sarif-unofficial-4ksIlfgF-py3.11/lib/python3.11/site-packages/jsonschema/validators.py", line 1147, in resolve_fragment
    document = document[part]
               ~~~~~~~~^^^^^^
KeyError: 'messageClass'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ek/.cache/pypoetry/virtualenvs/pylint-sarif-unofficial-4ksIlfgF-py3.11/bin/pylint2sarif", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ek/repos-wsl/pylint-sarif/src/pylint2sarif.py", line 41, in main
    p2s = Pylint2Sarif(args)
          ^^^^^^^^^^^^^^^^^^
  File "/home/ek/repos-wsl/pylint-sarif/src/pylint2sarif.py", line 137, in __init__
    self.sarif = builder.build_classes()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ek/.cache/pypoetry/virtualenvs/pylint-sarif-unofficial-4ksIlfgF-py3.11/lib/python3.11/site-packages/python_jsonschema_objects/__init__.py", line 135, in build_classes
    builder.construct(uri, defn, **kw)
  File "/home/ek/.cache/pypoetry/virtualenvs/pylint-sarif-unofficial-4ksIlfgF-py3.11/lib/python3.11/site-packages/python_jsonschema_objects/classbuilder.py", line 497, in construct
    ret = self._construct(uri, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ek/.cache/pypoetry/virtualenvs/pylint-sarif-unofficial-4ksIlfgF-py3.11/lib/python3.11/site-packages/python_jsonschema_objects/classbuilder.py", line 584, in _construct
    self.resolved[uri] = self._build_object(uri, clsdata, parent, **kw)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ek/.cache/pypoetry/virtualenvs/pylint-sarif-unofficial-4ksIlfgF-py3.11/lib/python3.11/site-packages/python_jsonschema_objects/classbuilder.py", line 665, in _build_object
    typ = self.resolve_type(ref, ".".join([nm, prop]))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ek/.cache/pypoetry/virtualenvs/pylint-sarif-unofficial-4ksIlfgF-py3.11/lib/python3.11/site-packages/python_jsonschema_objects/classbuilder.py", line 485, in resolve_type
    with self.resolver.resolving(ref) as resolved:
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/ek/.cache/pypoetry/virtualenvs/pylint-sarif-unofficial-4ksIlfgF-py3.11/lib/python3.11/site-packages/jsonschema/validators.py", line 1034, in resolving
    url, resolved = self.resolve(ref)
                    ^^^^^^^^^^^^^^^^^
  File "/home/ek/.cache/pypoetry/virtualenvs/pylint-sarif-unofficial-4ksIlfgF-py3.11/lib/python3.11/site-packages/jsonschema/validators.py", line 1081, in resolve
    return url, self._remote_cache(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ek/.cache/pypoetry/virtualenvs/pylint-sarif-unofficial-4ksIlfgF-py3.11/lib/python3.11/site-packages/jsonschema/validators.py", line 1099, in resolve_from_url
    return self.resolve_fragment(document, fragment)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ek/.cache/pypoetry/virtualenvs/pylint-sarif-unofficial-4ksIlfgF-py3.11/lib/python3.11/site-packages/jsonschema/validators.py", line 1149, in resolve_fragment
    raise exceptions._RefResolutionError(
jsonschema.exceptions._RefResolutionError: Unresolvable JSON pointer: 'definitions/messageClass'
```

`jsonschema` 4.18 changes how `$ref` is handled and that appears related to this, but 4.18.0 does work. The patch releases 4.18.1, 4.18.2, and 4.18.3 address regressions and shouldn't break anything, but I'm unsure if the bug is really in `jsonschema` or in `pylint-sarif-unofficial`.

Because I haven't yet dropped support for Python 3.7, but `jsonschema` 4.18 has, this bug is not observed when cloning this repository, installing it with `poetry install`, and testing it, and is further not observed even after `poetry update`, `poetry up`, or `poetry up --latest`. I first noticed this problem on [another project's CI](https://github.com/dmvassallo/EmbeddingScratchwork/actions/runs/5561170481/jobs/10158661211) (for https://github.com/dmvassallo/EmbeddingScratchwork/pull/208). I reproduced it as shown above by running `poetry shell` and, in the poetry-managed virtual environment, `pip install -U jsonschema`. I verified which versions are affected by running commands like `pip install -U jsonschema==4.18.0` and testing again.

Because 4.18.1, 4.18.2, and 4.18.3 address regressions present in 4.18.0, it is somewhat undesirable to pin `jsonschema` at 4.18.0, even as a temporary stopgap. The best thing to do would be for me to find the cause of the incompatibility in `pylint-sarif-unofficial` and fix it, and/or open a bug report for `jsonschema`. However, in the short term (which would become long term if I never get around to doing that), it might be better to pin `jsonschema` at 4.17.* and modify this repository and PyPI package's readme to advocate installing `pylint-sarif-unofficial` with `pipx` rather than in the project virtual environment. (That is itself because, if pinned, tools like Dependabot typically won't update it.)

**Comment by EliahKagan** [comment]
This project uses `jsonschema` indirectly through `python-jsonschema-objects`, which [does not currently support version 4.18.\* of `jsonschema`](https://github.com/cwacek/python-jsonschema-objects/issues/235).

Since the status of `python-jsonschema-objects` with `jsonschema` 4.18 is now tracked in https://github.com/cwacek/python-jsonschema-objects/issues/235, and versions >0.4.2 of `python-jsonschema-objects` [pin `jsonschema`](https://github.com/cwacek/python-jsonschema-objects/pull/236) to be [below 4.18](https://github.com/cwacek/python-jsonschema-objects/issues/237) such that this project no longer has to (#26), I'm closing this issue for now. It can be reopened if it turns out this project has any incompatibilities beyond those that are found to affect `python-jsonschema-objects` in general (or a new issue can be opened).

**Comment by AngellusMortis** [comment]
This has been resolved now if you want to test pylint-sarif with newer versions of both.
